#!/bin/bash
# RAG System Test Queries
# Test the current system before and after optimizations

echo "╔════════════════════════════════════════════════════╗"
echo "║        RAG System Quality Test Suite              ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

# Configuration
OPENWEBUI_URL="http://localhost:3000"

echo "🎯 Testing against: $OPENWEBUI_URL"
echo ""

# Test 1: Simple Fact Retrieval
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 1: Simple Fact Retrieval"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What is our revenue?'"
echo "Expected: '$50,000,000 for TechCorp' or '$2,500,000 for DemoTech'"
echo ""
echo "Login as alice.tenanta@gmail.com or demo.demotenant@gmail.com"
echo "Ask: What is our revenue?"
echo ""
read -p "Press Enter after testing..."

# Test 2: Multi-Fact Question
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 2: Multi-Fact Question"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What are our key financial metrics?'"
echo "Expected: Revenue, profit, expenses, EBITDA with specific numbers"
echo ""
echo "Ask: What are our key financial metrics?"
echo ""
read -p "Press Enter after testing..."

# Test 3: Employee Count
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 3: Employee Information"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'How many employees do we have?'"
echo "Expected: '450 employees' for TechCorp, '35 employees' for DemoTech"
echo ""
echo "Ask: How many employees do we have?"
echo ""
read -p "Press Enter after testing..."

# Test 4: Strategic Information
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 4: Strategic Projects"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What are our top projects?'"
echo "Expected: List of 3 projects with values"
echo ""
echo "Ask: What are our top projects?"
echo ""
read -p "Press Enter after testing..."

# Test 5: Percentage/Ratio Question
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 5: Percentage/Ratio"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What is our profit margin?'"
echo "Expected: Calculate from revenue and profit (28% for DemoTech)"
echo ""
echo "Ask: What is our profit margin?"
echo ""
read -p "Press Enter after testing..."

# Test 6: Negative Test (No Data)
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 6: No Context Available"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What is our stock price?'"
echo "Expected: 'I don't have information about stock price' (not in documents)"
echo ""
echo "Ask: What is our stock price?"
echo ""
read -p "Press Enter after testing..."

# Test 7: Tenant Isolation
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 7: Tenant Isolation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What is our revenue?' as DIFFERENT tenants"
echo "Expected: Different values for each tenant"
echo "  - TechCorp: $50M"
echo "  - DemoTech: $2.5M"
echo ""
echo "1. Login as alice.tenanta@gmail.com"
echo "   Ask: What is our revenue?"
echo "   Note the answer..."
echo ""
echo "2. Logout and login as demo.demotenant@gmail.com"
echo "   Ask: What is our revenue?"
echo "   Should be DIFFERENT value!"
echo ""
read -p "Press Enter after testing..."

# Test 8: Complex Query
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 8: Complex Multi-Part Query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'Compare our revenue, profit, and employee count'"
echo "Expected: All three metrics with calculations"
echo ""
echo "Ask: Compare our revenue, profit, and employee count"
echo ""
read -p "Press Enter after testing..."

# Test 9: Abbreviation/Synonym
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 9: Abbreviation Understanding"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Query: 'What's our EBITDA?'"
echo "Expected: Should find and return EBITDA value"
echo ""
echo "Ask: What's our EBITDA?"
echo ""
read -p "Press Enter after testing..."

# Test 10: Conversational Follow-up
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 10: Follow-up Question"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 First: 'What is our revenue?'"
echo "📝 Then: 'How does that compare to last year?'"
echo "Expected: Should remember context (or say no historical data)"
echo ""
echo "Ask two questions in sequence"
echo ""
read -p "Press Enter after testing..."

# Summary
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║              Test Summary                          ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "Rate each test result:"
echo "  ✅ Perfect - Got exact answer"
echo "  ⚠️  Partial - Got some info but incomplete"
echo "  ❌ Failed - Wrong or no answer"
echo ""
echo "Score Guide:"
echo "  9-10 tests ✅ = Excellent (85-100%)"
echo "  7-8 tests ✅  = Good (70-85%)"
echo "  5-6 tests ✅  = Fair (50-70%)"
echo "  <5 tests ✅   = Needs optimization!"
echo ""
echo "After testing, apply hybrid optimizations to improve!"
echo ""
